rainingsince:
  version-enable: false

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
jasypt:
  encryptor:
    password: eszxdrtfc!!!

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://39.105.81.49:3306/website?characterEncoding=utf-8&useSSL=false
    username: ENC(GooB1Ngyhhgs64yJerZ9nw==)
    password: ENC(YwdzA1tsUB/jrfqXfOgj1c5NpOzK/bpJ)
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
---
spring:
  profiles: pro
