rainingsince:
  version-enable: false

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
jasypt:
  encryptor:
    password: eszxdrtfc!!!

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.104.158.140:3306/website?characterEncoding=utf-8&useSSL=false
    username: ENC(3kodtUkYUR9V+6fO9o/Y9w==)
    password: ENC(eAkXPO+QQQrK7BWvaCirSl5ei7zXLS9M)
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://47.104.158.140:3306/website?characterEncoding=utf-8&useSSL=false
    username: ENC(3kodtUkYUR9V+6fO9o/Y9w==)
    password: ENC(eAkXPO+QQQrK7BWvaCirSl5ei7zXLS9M)
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
